# Generated by Django 4.0.3 on 2022-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whohaswhatapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_week',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
