# Generated by Django 4.0.3 on 2022-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whohaswhatapi', '0003_remove_lender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
