# Generated by Django 4.0.3 on 2022-03-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whohaswhatapi', '0005_item_pending_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pending_approval',
        ),
    ]
