# Generated by Django 4.0.3 on 2022-03-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whohaswhatapi', '0006_remove_item_pending_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whohaswhatapi.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to='whohaswhatapi.lender')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_renter', to='whohaswhatapi.lender')),
            ],
        ),
    ]
