# Generated by Django 4.0.3 on 2022-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whohaswhatapi', '0008_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestqueue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
